### ISSUE TITLE
announcements issue

### ISSUE THREAD

**Issue by masterfranky** [UserR00T/BP-Essentials#8]
reference update 2.4.4

announcements keep spamming every 10 seconds.
When checking the code it was set at 10 seconds and i changed it to a different number.
The announcements are still spamming the chat every 10 seconds despite trying various seconds changes

    // Time between annoucments, in seconds.
    "TimeBetweenAnnounce": 120,

**Comment by UserR00T** [comment]
You have to restart your server to change the announcer's interval, that is why it didn't change anything. I've defaulted the value to 10 because I was testing something but I forgot to revert it to 120, sorry. So if you just set it to 120, the restart your server (not reload) it should work fine then. I will try to make it in the next update to also change the announcer's interval on reload

Thanks!

**Comment by UserR00T** [comment]
Fixed issue in commit eddadb2cafabe6135c1963eb35e1b48cd373670b @ ``develop`` branch.
